AWSTemplateFormatVersion: '2010-09-09'
Description: Celeris Benchmark Worker Instances - Ephemeral spot instances for benchmarks

Parameters:
  RunId:
    Type: String
    Description: Unique identifier for this benchmark run

  Mode:
    Type: String
    AllowedValues:
      - fast
      - med
      - metal
    Description: Benchmark mode determines instance sizes

  Architecture:
    Type: String
    AllowedValues:
      - arm64
      - x86
    Description: CPU architecture for workers

  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: AZ for worker placement (server and client must be co-located)

  SpotPrice:
    Type: String
    Description: Maximum spot price bid

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for worker instances (must be in the specified AZ)

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group for workers

  InstanceProfileArn:
    Type: String
    Description: IAM instance profile ARN for workers

  C2Endpoint:
    Type: String
    Description: C2 server endpoint for reporting

  GitHubRepo:
    Type: String
    Default: goceleris/benchmarks
    Description: GitHub repository for benchmark code

  BenchmarkDuration:
    Type: String
    Default: '30s'
    Description: Duration for each benchmark

  BenchmarkMode:
    Type: String
    Default: all
    AllowedValues:
      - baseline
      - theoretical
      - all
    Description: Which servers to benchmark

Mappings:
  # Primary instance types
  InstanceTypes:
    fast:
      arm64Server: c6g.medium
      arm64Client: t4g.small
      x86Server: c5.large
      x86Client: t3.small
    med:
      arm64Server: c6g.2xlarge
      arm64Client: c6g.xlarge
      x86Server: c5.2xlarge
      x86Client: c5.xlarge
    metal:
      arm64Server: c6g.metal
      arm64Client: c6g.4xlarge
      x86Server: c5.metal
      x86Client: c5.9xlarge
  # Alternative instance types for capacity diversification
  InstanceTypesAlt1:
    fast:
      arm64Server: c7g.medium
      arm64Client: t4g.micro
      x86Server: c5a.large
      x86Client: t3a.small
    med:
      arm64Server: c7g.2xlarge
      arm64Client: c7g.xlarge
      x86Server: c5a.2xlarge
      x86Client: c5a.xlarge
    metal:
      arm64Server: c7g.metal
      arm64Client: c7g.4xlarge
      x86Server: c5d.metal
      x86Client: c5d.9xlarge
  # Second alternative for even more capacity options
  InstanceTypesAlt2:
    fast:
      arm64Server: c6g.large
      arm64Client: t4g.medium
      x86Server: c6i.large
      x86Client: t2.small
    med:
      arm64Server: c6g.4xlarge
      arm64Client: c6g.2xlarge
      x86Server: c6i.2xlarge
      x86Client: c6i.xlarge
    metal:
      arm64Server: m7g.metal
      arm64Client: c6g.8xlarge
      x86Server: c5n.metal
      x86Client: c5n.9xlarge

Conditions:
  IsArm64: !Equals [!Ref Architecture, arm64]

Resources:
  # Server Instance (Spot with instance type diversification for capacity)
  ServerSpotRequest:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-ec2-spot-fleet-tagging-role'
        TargetCapacity: 1
        AllocationStrategy: capacityOptimized
        InstanceInterruptionBehavior: terminate
        TerminateInstancesWithExpiration: true
        Type: maintain
        ExcessCapacityTerminationPolicy: default
        ReplaceUnhealthyInstances: false
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref ServerLaunchTemplate
              Version: !GetAtt ServerLaunchTemplate.LatestVersionNumber
            Overrides:
              # Primary instance type
              - AvailabilityZone: !Ref AvailabilityZone
                SubnetId: !Ref SubnetId
                InstanceType: !If
                  - IsArm64
                  - !FindInMap [InstanceTypes, !Ref Mode, arm64Server]
                  - !FindInMap [InstanceTypes, !Ref Mode, x86Server]
                SpotPrice: !Ref SpotPrice
              # Alternative 1 - different instance family for capacity diversification
              - AvailabilityZone: !Ref AvailabilityZone
                SubnetId: !Ref SubnetId
                InstanceType: !If
                  - IsArm64
                  - !FindInMap [InstanceTypesAlt1, !Ref Mode, arm64Server]
                  - !FindInMap [InstanceTypesAlt1, !Ref Mode, x86Server]
                SpotPrice: !Ref SpotPrice
              # Alternative 2 - yet another option for maximum capacity availability
              - AvailabilityZone: !Ref AvailabilityZone
                SubnetId: !Ref SubnetId
                InstanceType: !If
                  - IsArm64
                  - !FindInMap [InstanceTypesAlt2, !Ref Mode, arm64Server]
                  - !FindInMap [InstanceTypesAlt2, !Ref Mode, x86Server]
                SpotPrice: !Ref SpotPrice

  ServerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub 'celeris-server-${RunId}-${Architecture}'
      LaunchTemplateData:
        ImageId: !If
          - IsArm64
          - !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/arm64/hvm/ebs-gp2/ami-id}}'
          - !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}'
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        SecurityGroupIds:
          - !Ref SecurityGroupId
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 20
              VolumeType: gp3
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -euxo pipefail

            exec > >(tee /var/log/worker-init.log) 2>&1
            echo "=== Benchmark Server Bootstrap Started ==="

            # Metadata
            INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
            PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
            INSTANCE_TYPE=$(curl -s http://169.254.169.254/latest/meta-data/instance-type)
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION="${AWS::Region}"

            # Install dependencies
            apt-get update -qq
            apt-get install -y -qq curl jq

            # Kernel tuning for maximum network throughput
            echo "Applying kernel tuning..."

            # Increase socket buffer sizes
            sysctl -w net.core.rmem_max=16777216
            sysctl -w net.core.wmem_max=16777216
            sysctl -w net.core.rmem_default=1048576
            sysctl -w net.core.wmem_default=1048576

            # TCP buffer auto-tuning
            sysctl -w net.ipv4.tcp_rmem="4096 1048576 16777216"
            sysctl -w net.ipv4.tcp_wmem="4096 1048576 16777216"

            # Increase backlog for high connection rates
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.core.netdev_max_backlog=65535
            sysctl -w net.ipv4.tcp_max_syn_backlog=65535

            # Enable TCP fast open
            sysctl -w net.ipv4.tcp_fastopen=3

            # Reduce TIME_WAIT sockets
            sysctl -w net.ipv4.tcp_tw_reuse=1
            sysctl -w net.ipv4.tcp_fin_timeout=15

            # Disable slow start after idle
            sysctl -w net.ipv4.tcp_slow_start_after_idle=0

            # Increase max memory map areas
            sysctl -w vm.max_map_count=262144

            # Increase file descriptor limits
            ulimit -n 1000000
            echo "* soft nofile 1000000" >> /etc/security/limits.conf
            echo "* hard nofile 1000000" >> /etc/security/limits.conf

            # Download pre-built server binary from GitHub releases
            ARCH="${Architecture}"
            if [ "$ARCH" = "x86" ]; then ARCH="amd64"; fi
            echo "Downloading server binary for $ARCH..."
            curl -sL -o /usr/local/bin/server \
              "https://github.com/${GitHubRepo}/releases/download/latest/server-linux-$ARCH"
            chmod +x /usr/local/bin/server

            # Register with C2
            curl -sf -X POST "${C2Endpoint}/api/worker/register" \
              -H "Content-Type: application/json" \
              -d "{\"run_id\":\"${RunId}\",\"role\":\"server\",\"arch\":\"${Architecture}\",\"instance_id\":\"$INSTANCE_ID\",\"instance_type\":\"$INSTANCE_TYPE\",\"private_ip\":\"$PRIVATE_IP\",\"region\":\"$REGION\",\"az\":\"$AZ\"}"

            # Start server (control daemon mode with C2 heartbeat)
            echo "Starting server in control mode..."
            /usr/local/bin/server -mode control -port 8080 -control-port 9999 \
              -c2-endpoint "${C2Endpoint}" \
              -run-id "${RunId}" \
              -arch "${Architecture}"

            echo "=== Benchmark Server Exiting ==="
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub 'celeris-server-${RunId}-${Architecture}'
              - Key: Project
                Value: celeris-benchmarks
              - Key: Role
                Value: server
              - Key: RunId
                Value: !Ref RunId
              - Key: Architecture
                Value: !Ref Architecture

  # Client Instance (Spot with instance type diversification for capacity)
  ClientSpotRequest:
    Type: AWS::EC2::SpotFleet
    Properties:
      SpotFleetRequestConfigData:
        IamFleetRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-ec2-spot-fleet-tagging-role'
        TargetCapacity: 1
        AllocationStrategy: capacityOptimized
        InstanceInterruptionBehavior: terminate
        TerminateInstancesWithExpiration: true
        Type: maintain
        ExcessCapacityTerminationPolicy: default
        ReplaceUnhealthyInstances: false
        LaunchTemplateConfigs:
          - LaunchTemplateSpecification:
              LaunchTemplateId: !Ref ClientLaunchTemplate
              Version: !GetAtt ClientLaunchTemplate.LatestVersionNumber
            Overrides:
              # Primary instance type
              - AvailabilityZone: !Ref AvailabilityZone
                SubnetId: !Ref SubnetId
                InstanceType: !If
                  - IsArm64
                  - !FindInMap [InstanceTypes, !Ref Mode, arm64Client]
                  - !FindInMap [InstanceTypes, !Ref Mode, x86Client]
                SpotPrice: !Ref SpotPrice
              # Alternative 1 - different instance family for capacity diversification
              - AvailabilityZone: !Ref AvailabilityZone
                SubnetId: !Ref SubnetId
                InstanceType: !If
                  - IsArm64
                  - !FindInMap [InstanceTypesAlt1, !Ref Mode, arm64Client]
                  - !FindInMap [InstanceTypesAlt1, !Ref Mode, x86Client]
                SpotPrice: !Ref SpotPrice
              # Alternative 2 - yet another option for maximum capacity availability
              - AvailabilityZone: !Ref AvailabilityZone
                SubnetId: !Ref SubnetId
                InstanceType: !If
                  - IsArm64
                  - !FindInMap [InstanceTypesAlt2, !Ref Mode, arm64Client]
                  - !FindInMap [InstanceTypesAlt2, !Ref Mode, x86Client]
                SpotPrice: !Ref SpotPrice

  ClientLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub 'celeris-client-${RunId}-${Architecture}'
      LaunchTemplateData:
        ImageId: !If
          - IsArm64
          - !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/arm64/hvm/ebs-gp2/ami-id}}'
          - !Sub '{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}'
        IamInstanceProfile:
          Arn: !Ref InstanceProfileArn
        SecurityGroupIds:
          - !Ref SecurityGroupId
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 20
              VolumeType: gp3
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -euxo pipefail

            exec > >(tee /var/log/worker-init.log) 2>&1
            echo "=== Benchmark Client Bootstrap Started ==="

            # Metadata
            INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
            PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
            INSTANCE_TYPE=$(curl -s http://169.254.169.254/latest/meta-data/instance-type)
            AZ=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            REGION="${AWS::Region}"

            # Install dependencies
            apt-get update -qq
            apt-get install -y -qq curl jq

            # Kernel tuning for maximum network throughput
            echo "Applying kernel tuning..."

            # Increase socket buffer sizes
            sysctl -w net.core.rmem_max=16777216
            sysctl -w net.core.wmem_max=16777216
            sysctl -w net.core.rmem_default=1048576
            sysctl -w net.core.wmem_default=1048576

            # TCP buffer auto-tuning
            sysctl -w net.ipv4.tcp_rmem="4096 1048576 16777216"
            sysctl -w net.ipv4.tcp_wmem="4096 1048576 16777216"

            # Increase backlog for high connection rates
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.core.netdev_max_backlog=65535
            sysctl -w net.ipv4.tcp_max_syn_backlog=65535

            # Enable TCP fast open
            sysctl -w net.ipv4.tcp_fastopen=3

            # Reduce TIME_WAIT sockets
            sysctl -w net.ipv4.tcp_tw_reuse=1
            sysctl -w net.ipv4.tcp_fin_timeout=15

            # Disable slow start after idle
            sysctl -w net.ipv4.tcp_slow_start_after_idle=0

            # Increase max memory map areas
            sysctl -w vm.max_map_count=262144

            # Increase file descriptor limits
            ulimit -n 1000000
            echo "* soft nofile 1000000" >> /etc/security/limits.conf
            echo "* hard nofile 1000000" >> /etc/security/limits.conf

            # Download pre-built bench binary from GitHub releases
            ARCH="${Architecture}"
            if [ "$ARCH" = "x86" ]; then ARCH="amd64"; fi
            echo "Downloading bench binary for $ARCH..."
            curl -sL -o /usr/local/bin/bench \
              "https://github.com/${GitHubRepo}/releases/download/latest/bench-linux-$ARCH"
            chmod +x /usr/local/bin/bench

            # Register with C2
            curl -sf -X POST "${C2Endpoint}/api/worker/register" \
              -H "Content-Type: application/json" \
              -d "{\"run_id\":\"${RunId}\",\"role\":\"client\",\"arch\":\"${Architecture}\",\"instance_id\":\"$INSTANCE_ID\",\"instance_type\":\"$INSTANCE_TYPE\",\"private_ip\":\"$PRIVATE_IP\",\"region\":\"$REGION\",\"az\":\"$AZ\"}"

            # Wait for server to be ready (C2 will provide server IP)
            echo "Waiting for server assignment from C2..."
            while true; do
              RESPONSE=$(curl -sf "${C2Endpoint}/api/worker/assignment?run_id=${RunId}&arch=${Architecture}" || echo "{}")
              SERVER_IP=$(echo "$RESPONSE" | jq -r '.server_ip // empty')
              if [ -n "$SERVER_IP" ]; then
                echo "Got server IP: $SERVER_IP"
                break
              fi
              sleep 5
            done

            # Run benchmarks
            echo "Starting benchmarks against $SERVER_IP..."
            /usr/local/bin/bench \
              -mode "${BenchmarkMode}" \
              -duration "${BenchmarkDuration}" \
              -server-ip "$SERVER_IP" \
              -control-port 9999 \
              -c2-endpoint "${C2Endpoint}" \
              -run-id "${RunId}" \
              -arch "${Architecture}"

            # Report completion
            curl -sf -X POST "${C2Endpoint}/api/worker/complete" \
              -H "Content-Type: application/json" \
              -d "{\"run_id\":\"${RunId}\",\"role\":\"client\",\"arch\":\"${Architecture}\",\"instance_id\":\"$INSTANCE_ID\"}"

            echo "=== Benchmark Client Complete ==="
            shutdown -h now
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub 'celeris-client-${RunId}-${Architecture}'
              - Key: Project
                Value: celeris-benchmarks
              - Key: Role
                Value: client
              - Key: RunId
                Value: !Ref RunId
              - Key: Architecture
                Value: !Ref Architecture

Outputs:
  ServerSpotFleetId:
    Description: Server Spot Fleet Request ID
    Value: !Ref ServerSpotRequest

  ClientSpotFleetId:
    Description: Client Spot Fleet Request ID
    Value: !Ref ClientSpotRequest
